compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
num_processes: 1
machine_rank: 0
num_machines: 1

mixed_precision: bf16 # o "fp16"

deepspeed_config:
  train_micro_batch_size_per_gpu: 1
  train_batch_size: 1

  bf16:
    enabled: true

  zero_optimization:
    stage: 3
    offload_optimizer:
      device: cpu
      pin_memory: false
    offload_param:
      device: cpu
      pin_memory: false

  steps_per_print: 999999999
  gradient_accumulation_steps: 1
  disable_allgather: true
